services:

# Important Note: (for PostgreSQL 17 and below) Mount the data volume at /var/lib/postgresql/data
# Taken from https://hub.docker.com/_/postgres
  postgres:
    container_name: postgres
    image: postgres:16.0
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATA: /var/lib/postgresql/data 
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    
# https://hub.docker.com/_/mysql
  mysql:
    container_name: mysql
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce-network

# https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html#environment-variables
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.5
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 9080:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - ecommerce-network

# https://hub.docker.com/_/mongo
  mongo:
    container_name: mongo
    image: mongo:8.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce-network

# https://hub.docker.com/_/mongo-express
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    environment:

    # Config to change "admin:pass" you can look at the following link
    # https://stackoverflow.com/questions/77469509/change-default-adminpass-in-mongoexpress-within-docker
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/

      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017

      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_WEB_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_WEB_PASSWORD}
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - ecommerce-network

# https://hub.docker.com/r/maildev/maildev
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev:2.1.0
    restart: unless-stopped
    ports:
      - 1080:1080
      - 1025:1025

  
  sonarqube:
    container_name: sonarqube
    image: sonarqube:9-community
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - sonarqube-db
    networks:
      - ecommerce-network

  sonarqube-db:
    container_name: sonarqube-db
    image: postgres:16.0
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - 5434:5432
    volumes:
      - sonar_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  mongo_data:
  mysql_data:
  sonar_data:
